version: 2

jobs:
  unit_tests:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "cli/requirements.txt" }}-{{ checksum "test/teos/e2e/bitcoind_snap.sh" }}

      - run:
          name: Install dependencies
          command: |
            pyenv local 3.7.0
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install -r cli/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "cli/requirements.txt" }}-{{ checksum "test/teos/e2e/bitcoind_snap.sh" }}

      - run:
          name: Run teos unit tests
          command: |
            . venv/bin/activate
            pytest test/teos/unit/

      - run:
          name: Run common unit tests
          command: |
            . venv/bin/activate
            pytest test/common/unit

      - run:
          name: Run cli unit tests
          command: |
            . venv/bin/activate
            pytest test/cli/unit

  e2e_tests:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "cli/requirements.txt" }}-{{ checksum "test/teos/e2e/bitcoind_snap.sh" }}

      - run:
          name: Install bitcoind
          command: |
            sudo snap install `cat test/teos/e2e/bitcoind_snap.sh`

      - run:
          name: Run bitcoind
          command: |
            mkdir -p /home/circleci/snap/bitcoin-core/common/.bitcoin/
            cp test/teos/e2e/bitcoin.conf /home/circleci/snap/bitcoin-core/common/.bitcoin/
            /snap/bin/bitcoin-core.daemon

      - run:
          name: Setup teos
          command: |
            . venv/bin/activate
            python3 -m generate_keys -d ~/.teos/
            python3 -m generate_keys -n cli -d ~/.teos_cli/
            cp ~/.teos/teos_pk.der ~/.teos_cli/
            cp test/teos/e2e/teos.conf ~/.teos/

      - run:
          name: Run e2e tests
          command: |
            . venv/bin/activate
            pytest test/teos/e2e/

workflows:
  version: 2

  run_tests:
    jobs:
      - unit_tests
      - e2e_tests:
          requires:
            - unit_tests